#!/bin/sh
#
# pngclean -- clean PNG files produced by Mathematica
#
# When Mathematica produces PNG files with transparency, the edges often
# acquire rasterization artifacts.  So we add a white background to the
# PNG, trim it, and then optimize it.
#

[ "$*" ] || {
    echo >&2 "usage: ${0##*/} <png>..."
    exit 1
}

for png
do
    mogrify -flatten "$png"
    mogrify -trim "$png"
    optipng -clobber "$png"
done
